void setup() {
    Serial.begin(9600);
}

void loop() {
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 16\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 15\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 14\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 13\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 12\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 11\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 10\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 9\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 8\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 7\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 6\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 5\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 4\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 3\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 2\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 1\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  Serial.print("$CLEAR\r\n");
  Serial.print("$GO 1 0\r\n");
  Serial.print("$PRINT PARK SANG MIN\r\n");
  Serial.print("$CURSOR 1 1\r\n");
  delay(500);
  
}
